import Anthropic from "@anthropic-ai/sdk";
import { config, PROMPT_TEMPLATE } from "./config.ts";
import type { WPPost } from "./wordpress.ts";

export interface ImagePrompt {
  scene: string;
  mascot: string;
  scene_description: string;
  full_prompt: string;
}

export interface PromptResult {
  prompts: ImagePrompt[];
}

const SYSTEM_PROMPT = `You are a creative director for a tech blog. Given a blog post, you design miniature diorama scenes for blog cover thumbnails.

Translate the post's core idea into a tiny physical scene that tells the story at a glance. Just place the mascot in a scene — the scene itself communicates the message.

## How to think about scenes

1. **Find the core metaphor.** "Pairing with AI agents" → mascot and a tiny robot side by side at a desk. "Debugging production" → mascot next to a cracked server. Don't restate the topic — show it.
2. **Use 1-3 simple props.** A desk, a laptop, a whiteboard, a server rack. The fewer props, the stronger the image.
3. **Add a second character when it helps.** A tiny robot can represent an AI, a teammate, an agent.

## Qwen prompting rules

The images are generated by Qwen Image Edit (LLM-based text encoder). Write natural language sentences, not tags.

- **2-3 short sentences**, under 40 words total.
- Use **camera-relative depth layering**: what's in the foreground, what's in the background, where the camera is.
- Refer to the mascot as **"a small mascot from the reference image"** and any secondary character as **"a tiny robot"**.
- Don't prescribe poses or actions — just place characters and props in the scene and let the image model figure out the rest.
- **Avoid**: literal topic restatements, vague scene-setting, meta-descriptions, filler adjectives, boilerplate.

## Example

Post: "Pairing with AI coding agents — navigator/driver model"

Good:
"A small mascot from the reference image and a tiny robot sit side by side at a desk, both facing a laptop screen. The camera is positioned opposite them, showing the back of the laptop lid in the foreground and the two characters in the background."

Bad:
"The mascot is pair programming with an AI assistant at a modern development workspace, collaborating on code shown on a screen."

## Mascot characters

| ID | Description | Best for |
|---|---|---|
| miner | Mining helmet, goggles, backpack — rugged look | Building, debugging, infrastructure, DevOps, hands-on work |
| hat | Tech hat and glasses — intellectual look | Architecture, planning, code review, learning, thinking |

## Output rules

- Generate exactly 2-3 scenes
- Each scene is a **visual metaphor** — a diorama that captures the post's essence
- Simple props, no clutter
- scene_description will be interpolated into a locked style template — just describe the diorama, nothing else`;

function buildFullPrompt(sceneDescription: string): string {
  const scene = sceneDescription.replace(/\.$/, "");
  return PROMPT_TEMPLATE.replace("[SCENE]", scene);
}

export async function generatePrompts(post: WPPost): Promise<PromptResult> {
  const client = new Anthropic({ apiKey: config.anthropicApiKey });

  const message = await client.messages.create({
    model: "claude-sonnet-4-20250514",
    max_tokens: 1024,
    system: SYSTEM_PROMPT,
    tools: [
      {
        name: "generate_prompts",
        description:
          "Generate image prompts for blog cover thumbnails based on the post content.",
        input_schema: {
          type: "object" as const,
          properties: {
            prompts: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  scene: {
                    type: "string",
                    description:
                      "Short label for the scene (2-5 words, e.g. 'mascot and robot at desk')",
                  },
                  mascot: {
                    type: "string",
                    enum: ["miner", "hat"],
                    description:
                      "Which mascot to use: 'miner' (rugged) or 'hat' (intellectual)",
                  },
                  scene_description: {
                    type: "string",
                    description:
                      "2-3 sentences (under 40 words). Place the mascot and props in a scene with camera-relative depth. Use 'a small mascot from the reference image'. Don't prescribe poses.",
                  },
                },
                required: ["scene", "mascot", "scene_description"],
              },
              minItems: 2,
              maxItems: 3,
            },
          },
          required: ["prompts"],
        },
      },
    ],
    tool_choice: { type: "tool", name: "generate_prompts" },
    messages: [
      {
        role: "user",
        content: `Generate thumbnail prompts for this blog post:

Title: ${post.title}

Excerpt: ${post.excerpt}

Content:
${post.content.slice(0, 4000)}`,
      },
    ],
  });

  const toolBlock = message.content.find((block) => block.type === "tool_use");
  if (!toolBlock || toolBlock.type !== "tool_use") {
    throw new Error("Claude did not return a tool_use block");
  }

  const raw = toolBlock.input as {
    prompts: Array<{
      scene: string;
      mascot: string;
      scene_description: string;
    }>;
  };

  return {
    prompts: raw.prompts.map((p) => ({
      ...p,
      full_prompt: buildFullPrompt(p.scene_description),
    })),
  };
}
