import Anthropic from "@anthropic-ai/sdk";
import { config, PROMPT_TEMPLATE } from "./config.ts";
import type { WPPost } from "./wordpress.ts";

export interface ImagePrompt {
  scene: string;
  variation: string;
  scene_description: string;
  full_prompt: string;
}

export interface PromptResult {
  prompts: ImagePrompt[];
}

const SYSTEM_PROMPT = `You are a creative director for a tech blog. Given a blog post, you generate scene descriptions for blog cover thumbnails.

The images are generated by **Qwen Image Edit**, which uses an LLM as its text encoder. This means prompts must be written as natural language sentences, NOT comma-separated tags or keyword lists.

## Qwen prompting rules

- Write **1-3 sentences** of scene description. Coherence drops after ~50 words.
- Use **explicit spatial relationships**: relative positions ("on the left side", "in the foreground"), depth layering ("foreground", "midground", "background"), and camera positioning ("camera positioned opposite them").
- Refer to the mascot as **"mascot from the reference image"** — never describe its appearance explicitly; Qwen reads it from the reference.
- Front-load the most important information. The model prioritizes what comes first.
- **Avoid**: vague adjectives ("beautiful", "stunning"), boilerplate quality words ("masterpiece, 4k"), keyword lists without sentence structure, contradictory styles.

## Mascot variations

Pick the best pose/context for each scene:

| Variation | Use when |
|---|---|
| handshake | Partnerships, integrations, collaborations |
| warning with a megaphone | Announcements, important updates, breaking changes |
| celebrating at a podium | Releases, milestones, achievements |
| two cooperating | Teamwork, pair programming, mentorship |
| detective investigating | Debugging, analysis, deep-dive investigations |
| questioning | FAQ, troubleshooting, common questions |
| happy | General positive posts, success stories |
| thumbs up | Recommendations, endorsements, best practices |
| reading | Documentation, tutorials, learning resources |
| on laptop | Coding tutorials, development workflows |
| presenting slides | Architecture explanations, design decisions |
| thinking | Problem-solving, trade-offs, evaluations |
| on a meeting | Discussions, planning, strategy |
| holding a warning | Security alerts, pitfalls, caveats |

## Output rules

- Generate exactly 2-3 scenes
- Each scene should be distinct and capture a different aspect of the post
- Scenes describe physical actions/settings the mascot is in (not abstract concepts)
- Return scene_description as the natural-language sentence(s) describing the scene — it will be interpolated into a locked style template`;

function buildFullPrompt(sceneDescription: string): string {
  const scene = sceneDescription.replace(/\.$/, "");
  return PROMPT_TEMPLATE.replace("[SCENE]", scene);
}

export async function generatePrompts(post: WPPost): Promise<PromptResult> {
  const client = new Anthropic({ apiKey: config.anthropicApiKey });

  const message = await client.messages.create({
    model: "claude-sonnet-4-20250514",
    max_tokens: 1024,
    system: SYSTEM_PROMPT,
    tools: [
      {
        name: "generate_prompts",
        description:
          "Generate image prompts for blog cover thumbnails based on the post content.",
        input_schema: {
          type: "object" as const,
          properties: {
            prompts: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  scene: {
                    type: "string",
                    description:
                      "Short label for the scene (2-5 words, e.g. 'debugging with magnifying glass')",
                  },
                  variation: {
                    type: "string",
                    description:
                      "Mascot variation from the table (e.g. 'detective investigating', 'on laptop')",
                  },
                  scene_description: {
                    type: "string",
                    description:
                      "1-3 natural language sentences describing the scene with explicit spatial relationships. Refers to the mascot as 'mascot from the reference image'. This gets interpolated into the style template.",
                  },
                },
                required: ["scene", "variation", "scene_description"],
              },
              minItems: 2,
              maxItems: 3,
            },
          },
          required: ["prompts"],
        },
      },
    ],
    tool_choice: { type: "tool", name: "generate_prompts" },
    messages: [
      {
        role: "user",
        content: `Generate thumbnail prompts for this blog post:

Title: ${post.title}

Excerpt: ${post.excerpt}

Content:
${post.content.slice(0, 4000)}`,
      },
    ],
  });

  const toolBlock = message.content.find((block) => block.type === "tool_use");
  if (!toolBlock || toolBlock.type !== "tool_use") {
    throw new Error("Claude did not return a tool_use block");
  }

  const raw = toolBlock.input as {
    prompts: Array<{
      scene: string;
      variation: string;
      scene_description: string;
    }>;
  };

  return {
    prompts: raw.prompts.map((p) => ({
      ...p,
      full_prompt: buildFullPrompt(p.scene_description),
    })),
  };
}
